import smtplib
import pandas as pd
import os
import glob
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

# --- CONFIGURATION ---
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SENDER_EMAIL = "vishwajeetchakaravarthi@gmail.com"
# RECEIVERS: Add your dad's email here too!
RECEIVERS = ["vishwajeetchakaravarthi@gmail.com"] 

def send_email():
    print("📧 Starting Email Bot...")
    
    # 1. GET PASSWORD
    password = os.environ.get("EMAIL_PASSWORD")
    if not password:
        print("❌ Error: EMAIL_PASSWORD secret is missing.")
        exit(1)

    # 2. FIND DATA
    files = glob.glob("*_rankings.csv")
    if not files:
        print("❌ Error: No ranking files found.")
        exit(1)

    filename = files[0]
    print(f"   ✅ Found Data: {filename}")
    
    try:
        df = pd.read_csv(filename)
        
        # --- THE FIX: DYNAMIC COLUMN SELECTION ---
        # Instead of hardcoding 'PE_Ratio', we pick useful columns that actually exist.
        desired_cols = ['Ticker', 'Close', 'Alpha_Score', 'RSI', 'Data_Source', 'Last_Updated']
        
        # Only keep columns that are present in the CSV
        available_cols = [c for c in desired_cols if c in df.columns]
        
        # detailed_view is the table we send in email
        top_picks = df[available_cols].head(10)
        
    except Exception as e:
        print(f"❌ Error reading CSV: {e}")
        exit(1)

    # 3. COMPOSE EMAIL
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"📈 AlphaQuant Intel: {datetime.now().strftime('%Y-%m-%d')}"
    msg["From"] = SENDER_EMAIL
    msg["To"] = ", ".join(RECEIVERS)

    # HTML Table with some style
    html_content = f"""
    <html>
      <body style="font-family: Arial, sans-serif;">
        <h2 style="color: #2E86C1;">🚀 Daily Market Intelligence</h2>
        <p>Top high-conviction setups generated by the AlphaQuant Engine.</p>
        
        {top_picks.to_html(index=False, border=1, classes='table', justify='center')}
        
        <p style="margin-top: 20px; font-size: 12px; color: gray;">
           Data Source: {top_picks.iloc[0]['Data_Source'] if 'Data_Source' in top_picks.columns else 'N/A'} <br>
           Updated: {top_picks.iloc[0]['Last_Updated'] if 'Last_Updated' in top_picks.columns else 'Unknown'}
        </p>
      </body>
    </html>
    """
    part = MIMEText(html_content, "html")
    msg.attach(part)

    # 4. SEND
    try:
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        server.login(SENDER_EMAIL, password)
        server.sendmail(SENDER_EMAIL, RECEIVERS, msg.as_string())
        server.quit()
        print("✅ Email Sent Successfully!")
    except Exception as e:
        print(f"❌ Login Failed: {e}")
        exit(1)

if __name__ == "__main__":
    send_email()
